### ISSUE TITLE
Backup to swift (OpenStack object storage)

### ISSUE THREAD

**Issue by szepeviktor** [jborg/attic#160]
Do you plan to support remote backup targets? (without fuse)

**Comment by jborg** [comment]
> Do you plan to support remote backup targets? (without fuse)
Do you mean without having to install Attic on the remote host? Otherwise this already works:
https://attic-backup.org/quickstart.html#remote-repositories

An Attic repository is basically a transactional key value store. And as far as I know neither OpenStack or S3 support transactions. So I'm afraid it would be fairly difficult to build an efficient transactional key value store on top of them.
