### ISSUE TITLE
wrong behaviour with 2-char directory prefixes

### ISSUE THREAD

**Issue by ThomasWaldmann** [jborg/attic#268]
A bug discovered and fixed by @lealanko in PR #265.

Here's how to reproduce:
```
$ mkdir ab
$ touch ab/foo
$ attic init /tmp/attic
$ attic create /tmp/attic::1 ab/
$ attic list /tmp/attic::1
drwxrwxr-x tw     tw            0 Apr 04 10:58 ab
-rw-rw-r-- tw     tw            0 Apr 04 10:58 foo
(attic-env)tw@tux:~/w/attic$ mkdir ex
(attic-env)tw@tux:~/w/attic$ cd ex
(attic-env)tw@tux:~/w/attic/ex$ attic extract /tmp/attic::1
(attic-env)tw@tux:~/w/attic/ex$ ls -lR
.:
total 4
drwxrwxr-x 2 tw tw 4096 Apr  4 10:58 ab
-rw-rw-r-- 1 tw tw    0 Apr  4 10:58 foo

./ab:
total 0
```

You see, file "foo" ends up on the same level as directory "ab", NOT inside directory "ab".

**Comment by camh-** [comment]
I independently came across this problem last week and made my own fix before noticing this issue existed with a pull request. My fix is at https://github.com/camh-/attic/tree/fix-make_path_safe. Please consider this for two reasons:
1) I've used a raw string for the regex. Always use raw strings for regexes, otherwise some backslashes need to be escaped, and others don't.
2) I've added test cases that fail without the fix in. Test-first, and all that.

Let me know if you want it and I'll create the pull request.
