### ISSUE TITLE
Appeasing attic when moving repo / changing ownership of a repo / deleting user's .cache/attic?

### ISSUE THREAD

**Issue by danmbox** [jborg/attic#299]
I've moved an unencrypted repository; subsequently, since attic kept "remembering" where the repo used to live (and refusing to work), I deleted ~/.cache/attic. Now I can't add any backups to the repository. All I get is

> Warning: Attempting to access a previously unknown unencrypted repository
> attic: Error: Cache initialization aborted

How do I regain control of my repository? I really appreciate the thoughtful security measures, but there has to be a way for the user to remove the roadblocks that the software has put in place to make sure I don't unintentionally back up without a passphrase.

Also, how do I move a repository (or transfer ownership to a different Linux user) without triggering this nightmare?

**Comment by jborg** [comment]
Since you're not seeing the interactive "Do you want to continue? [yN] " question i guess you're invoking attic from a script without any controlling terminal.

The easiest way to resolve this is to once manually invoke any attic command that uses the cache (create, delete, prune or info) and answer YES at the prompt.

If that is not possible you can set the "ATTIC_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes" environment variable in your script. That should also do the trick.

I hope this solves your problem

**Comment by danmbox** [comment]
Thanks, setting `ATTIC_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK` works. Is it safe to use the same repo sequentially from multiple accounts (each with a different, possibly outdated cache)?

Note that without `ATTIC_UNKNOWN*`, the behavior is quite counterintuitive:

* From the command line, `attic info repo::snapshot` dies with
> Warning: Attempting to access a previously unknown unencrypted repository
> attic: Error: Cache initialization aborted

* However, `ls | attic info repo::snapshot` dies with
> Warning: Attempting to access a previously unknown unencrypted repository
> Do you want to continue? [yN] attic: Error: Cache initialization aborted

This is with attic=0.15, after `rm -rf ~/.attic/cache/` , regardless of whether `snapshot` exists or not.

**Comment by jean** [comment]
We're encountering this, but we are running `attic` manually from a bash prompt on Ubuntu, and do not get a prompt.

**Comment by n3storm** [comment]
FYI: Updating to Attic-0.16 in Debian Jessie Stable solved this issue.
