### ISSUE TITLE
Graphical frontend

### ISSUE THREAD

**Issue by finid** [jborg/attic#3]
Would be nice to have a graphical interface for Attic.

**Comment by leoetlino** [comment]
Since Attic already supports mounting an archive as a FUSE filesystem, I think a GUI for configuring backups would be the most useful.

Personally, I think Attic is simple, efficient and powerful enough as it is now, but having something like [this](http://torsion.org/hg/atticmatic/) or even a configuration GUI wouldn't be bad either.
